### ISSUE TITLE
Using BinDeps to install Thrift compiler

### ISSUE THREAD

**Issue by jpfairbanks** [tanmaykm/Thrift.jl#20]
Hello @tanmaykm,

Currently you use a script to install the Thrift compiler for travis-ci, would it make sense to convert that to a `./deps/build.jl` script possible using  Bindeps to handle the dependencies on libssl-dev, flex, bison, and libboost-all-dev?

**Comment by tanmaykm** [comment]
Thanks @jpfairbanks for the suggestion.

The script used to set things up for travis builds Thrift with a fixed set of options and language support. I think in most setups, people may want to do that on their own and add languages they want to work with. My thought has been to eventually add the Julia plugin to `apache/thrift` (see #2).

In any case, it is definitely a good idea to use BinDeps to detect and build Thrift if necessary (with a default set of options). Will be happy to accept a PR if you have something going.

**Comment by jpfairbanks** [comment]
Do you want this to use your fork of thrift? I used the latest release with your compiler plugin as described in the readme of this project, but then the thrift executable did not pick up the `-gen jl` option.

It also looks like https://github.com/JuliaLang/BinDeps.jl/issues/213 will be helpful because we need the bison executable to build thrift and the thrift executable rather than as a shared library.

**Comment by tanmaykm** [comment]
I was using the fork just for convenience and to avoid surprises. Using the latest release is better. The only change in my fork was to `t_jl_generator.cc`.

You seem to have found the solution in #21. :+1:
