### ISSUE TITLE
Windows compatability

### ISSUE THREAD

**Issue by davidanthoff** [tanmaykm/Thrift.jl#29]
Would be great if this could work on Windows. It is not clear to me what needs to be done for that to happen.

It seems that there are two things: one is to use Thrift.jl to compile things, but that doesn't necessary need to work on Windows, right? One could compile these files on some other system, and then ship them in say Parquet.jl? So maybe it would be enough to get things working on Windows just for the use case of these files?

**Comment by tanmaykm** [comment]
It will be good to have the compiler working on Windows as well, needs `deps/build.jl` to work on Windows. I don't have a Windows environment available with me to develop/maintain that. A PR would be welcome.

But yes, thrift files compiled on a linux system can be used on Windows as well. In case of Parquet.jl, the thrift specification here (https://github.com/JuliaComputing/Parquet.jl/tree/master/thrift) is already converted to files here (https://github.com/JuliaComputing/Parquet.jl/tree/master/src/PAR2) by the thrift compiler.

**Comment by tanmaykm** [comment]
Package now installs without errors on Windows after #40 and #42.

However a pre-built Thrift compiler is not installed yet on Windows (couldn't get it to build with BinaryBuilder).

**Comment by visr** [comment]
Have you already attempted to build this on the new BinaryBuilder? Even if it doesn't work everywhere at first, the folks over at Yggdrasil will happily help you pushing it over the edge.

If I understand correctly from JuliaThriftBuilder this would first need Bison right? I don't see where it is used though. Bison is not yet on Yggdrasil. Boost is listed as a requirement in the Thrift docs but I don't see that as a dependency in JuliaThriftBuilder (though Boost is in Yggdrasil).

https://thrift.apache.org/docs/install/
https://thrift.apache.org/docs/BuildingFromSource
https://github.com/tanmaykm/JuliaThriftBuilder/blob/master/build_tarballs.jl
https://github.com/tanmaykm/BisonBuilder/blob/master/build_tarballs.jl

**Comment by tanmaykm** [comment]
Thanks @visr. No, I haven't yet attempted to build it with the new BinaryBuilder. The Thrift docs do mention `WinFlexBison` as a requirement for Windows: http://thrift.apache.org/docs/install/.

It's great if Boost is already there in Yggdrasil. I am not sure if it would need the header files though - I see that `libboost-all-dev` is what I had used [earlier](https://github.com/tanmaykm/Thrift.jl/blob/master/test/setup_thrift_compiler.sh).

**Comment by tanmaykm** [comment]
should be working after #60, released with [v0.7.0](https://github.com/JuliaRegistries/General/pull/14932)
