### ISSUE TITLE
compiler extension build fails with thrift 0.9.2

### ISSUE THREAD

**Issue by cberzan** [tanmaykm/Thrift.jl#3]
```
src/generate/t_jl_generator.cc:251:9: error: ‘class t_enum’ has no member named ‘resolve_values’
```

The `resolve_values` method has been removed in [this commit](https://git-wip-us.apache.org/repos/asf?p=thrift.git;a=commit;h=ae0b22cc29a329f5e094c37d8fff166d01b6fab5).

I commented out line 251 and the build succeeded, but I don't know if it's still behaving correctly, since I don't use enums in my thrift definition files.

**Comment by tanmaykm** [comment]
Thanks!
Fixed by #4
