### ISSUE TITLE
Confusing README

### ISSUE THREAD

**Issue by randyzwitch** [tanmaykm/Thrift.jl#36]
I'm trying to get started with this package, so I can see if I can build Thrift bindings for MapD in Julia. From the README, it implies that you need to install and build thrift, but it looks like `Pkg.add("Thrift")` already does so.

So, do you actually need to build thrift from source or is that out-of-date?

**Comment by randyzwitch** [comment]
I realized that I can build the 'hello' example using the thrift compiler that Thrift.jl builds, so now I'm just commenting the README is out of date. If I get far enough where I think I understand it, I'll submit a PR.

**Comment by tanmaykm** [comment]
Yes, the README is outdated.

`Pkg.add("Thrift")` will build a version of the compiler. It does that with a specific set of options (disabling most other languages to make the build faster and less error prone), and a specific version of the sources (the one it was last tested with).

That's should be sufficient in most cases, but the steps mentioned in README can be followed if one wants to build it differently.

Thanks for raising an issue.
