### ISSUE TITLE
Enabling logging?

### ISSUE THREAD

**Issue by randyzwitch** [tanmaykm/Thrift.jl#56]
I'm still trying to debug #52, and tried to enable debugging, but it's not clear to me if you are using the normal logging mechanisms or something custom. I found this commented out code:

https://github.com/tanmaykm/Thrift.jl/blob/master/src/Thrift.jl#L38-L47

So my question is, how do I enable logging for Thrift, so I can see all the `at-logmsg()` messages?

**Comment by randyzwitch** [comment]
Any chance you can help me with this @tanmaykm?

**Comment by tanmaykm** [comment]
Sorry, didn't notice this earlier.

To enable logging, you could change the `macro logmsg` to include a body that does `@debug` or `println`.

This (`macro logmsg`) was done before the current `Logging` module came in to Base. It needs to be updated to the new Julia Logging package. That will allow controlling logging without having to edit code. I think I can do that over the weekend.
